# Writes a C++ source that defines the bytes of a binary file as an array, so
# the file ships inside the executable instead of next to it.
#
#   cmake -DINPUT=<file> -DOUTPUT=<file.cpp> -DSYMBOL=<name> -P EmbedFile.cmake
#
# defines "extern const unsigned char <name>[]" and "extern const size_t <name>_size".

file(READ "${INPUT}" hex HEX)
string(LENGTH "${hex}" hexLength)
math(EXPR size "${hexLength} / 2")

# "0a1b" -> "0x0a,0x1b," with a line break every 16 bytes
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){16})" "\\1\n" bytes "${bytes}")

file(WRITE "${OUTPUT}"
"// Generated by cmake/EmbedFile.cmake from ${INPUT}. Do not edit.
#include <cstddef>

extern const unsigned char ${SYMBOL}[] = {
${bytes}
};
extern const size_t ${SYMBOL}_size = ${size};
")
